### ISSUE TITLE
Problema com a função simupetri.

### ISSUE THREAD

**Issue by mateuslenier** [arcardosoc/discreta12petriautom#15]
Ponteiros das listas apontando pro vazio. Segmentation fault a partir da linha 165.

**Comment by drbeco** [comment]
Erro interessante. Mais detalhes do problema?

**Comment by mateuslenier** [comment]
Inicialmente o código estava apresentando problemas na criação das listas encadeadas, como apresentado em um bug anterior o código estava criando uma lista com todas as variáveis zero.

**Comment by mateuslenier** [comment]
para solucionar esse problema foi colocado ponteiros nas declaração das variáveis do tipo structs(lugartoken,lugartransicao,transicaolugar) para apontar para um espaço da memoria e resolver esse problema
.

**Comment by mateuslenier** [comment]
Mas com a resolução desse problema algumas partes do código teve que ser alteradas como na inserção de novos listas no encadeamento e na simupetri que faz buscas nas lista para simular a rede.

**Comment by mateuslenier** [comment]
As alterações foram feitas. A inserções tiveram um bug inicial, não estava encadeando as listas, mas logo foram corrigidas,mas ao compilar novamente esse bug apareceu.

**Comment by mateuslenier** [comment]
Como esse bug não aparece na compilação foi utilizado o comando valgrind ./ex12.x --leak-ch                                                                                        eck=full para verificar aonde estava o erro. O valgrind especificou que : Thread 2:
Invalid read of size 4
at 0x400DC3: simupetri (ex12.c:165)
Address 0x8 is not stack'd, malloc'd or (recently) free'd

Process terminating with default action of signal 11 (SIGSEGV)
Access not within mapped region at address 0x8
at 0x400DC3: simupetri (ex12.c:165)
If you believe this happened as a result of a stack
overflow in your program's main thread (unlikely but
possible), you can try to increase the size of the
main thread stack using the --main-stacksize= flag.
The main thread stack size used in this run was 8388608.

**Comment by mateuslenier** [comment]
Resolvido,só foi necessário retirar as variáveis temporárias.
