### ISSUE TITLE
Inicialização de variáveis e chamada das funções

### ISSUE THREAD

**Issue by mateuslenier** [arcardosoc/discreta12petriautom#4]
Acabei de adicionar os protótipos das funções em conjunto com a struct que será a variável base do programa. Ainda falta inicializar esse struct na main e colocar as chamadas das funções nos locais exatos de funcionamento.

**Comment by drbeco** [comment]
Todo issue deve estar  associado a um milestone . (menu da direita :point_right: )

**Comment by arcardosoc** [comment]
Struct inicializada e chamada das funções colocadas na main.
